version: '3.7'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data/customers
      - HOSTNAME_EXTERNAL=localstack
      - SNS_WITH_SQS=customer-indexer
    volumes:
      - ./localstack_setup:/docker-entrypoint-initaws.d/
      - /tmp/localstack/customers:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'

  application:
    build:
      context: .
    image: customers
    hostname: customers
    container_name: customers
    ports:
      - "8080:8080"
    init: true
    depends_on:
      - postgres
      - localstack
    environment:
      DATASOURCE_URL: $DATASOURCE_URL

  postgres:
    container_name: customers_postgres
    hostname: customers_postgres
    restart: always
    image: postgres:11-alpine
    command: [ "-c", "max_connections=200" ]
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql11/data
    environment:
      POSTGRES_DB: customers
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres:
  localstack:
